# Generated by Django 4.2.4 on 2023-08-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_api', '0003_alter_task_description_alter_task_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
