# Generated by Django 4.2.4 on 2023-08-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistmodels',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
